config/routes.rb
Outft::Application.routes.draw do
  
  get "sessions/new"
  
  resources :dashboard
  resources :outfits
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    resources :pieces
    resources :outfits
    member do
      get :following, :followers
      get :svpply
      post :multiple_create
    end
  end
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  get "home/index"

  root :to => 'home#index'

end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :pieces
  default_scope :order => "created_at DESC"
  
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  
  def index
    @user = User.find(params[:user_id])
    @outfits = @user.outfits
    @title = "Outfits"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @outfits }
    end
  end
  
  def new
    @outfit = Outfit.new
    @user = current_user
    @title = "New Outfit"
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @outfit }
    end
  end
  
  def show
    @outfit = Outfit.find(params[:id])
    @title = @outfit.title
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @outfit }
    end
  end
  
  def create
    @user = User.find(params[:user_id])
    @outfit = @user.outfits.create(params[:outfit])
    redirect_to user_path(@user)
  end
  
  def destroy
    @user = User.find(params[:user_id])
    @outfit = @user.outfits.find(params[:id])
    @outfit.destroy
    redirect_to user_path(@user)
  end
  
  
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_form.html.erb
<div id = "piece_selector" >
	<ul >
		<% @user.pieces.each do |piece| %>
		<li value = <%= piece.id %> >
			<%= image_tag(piece.image.url(:thumb)) %> 
		</li>
		<% end %>
	</ul>
</div>

<%= form_for([@user, @user.outfits.build]) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="text">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div id = "hidden_fields">
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outfits/_outfit.html.erb
<div id = "outfit-feed">
<% outfit.pieces.each do |piece| %>
	<%= render piece %>
<% end %>

<p>
  <b>Title:</b>
  <%= outfit.title %>
</p>

<p>
  <b>Description:</b>
  <%= outfit.description %>
</p>

<p>
  <%= link_to 'Destroy Outfit', [outfit.user, outfit],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>
</div>

app/views/outfits/index.html.erb
<h1>Listing outfits</h1>

<table>
  <tr>
    <th>Title</th>
    <th>desc</th>
	<th>view</th>

  </tr>

<% @outfits.each do |outfit| %>
  <tr>
    <td><%= outfit.title %></td>
    <td><%= outfit.description %></td>
	<td><%= link_to "view", user_outfit_path(outfit.user, outfit) %></td>

  </tr>
<% end %>
</table>

app/views/outfits/new.html.erb
<div id = "new-outfit">
<%= render "form" %>
</div>

app/views/outfits/show.html.erb
<%= render @outfit %>