config/routes.rb
Outft::Application.routes.draw do
  
  get "sessions/new"
  
  resources :dashboard
  resources :outfits
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    resources :pieces
    resources :outfits
    member do
      get :following, :followers
      get :svpply
      post :multiple_create
    end
  end
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  get "home/index"

  root :to => 'home#index'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :avatar, :location, :about
  
  extend FriendlyId
  friendly_id :name, :use => :slugged
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40}
  validates :name , :presence => true, :length => { :maximum => 50 }, :uniqueness => { :case_sensitive => false }
  validates :email, :presence => true, :uniqueness => { :case_sensitive => false }
  
  has_attached_file :avatar, :styles => { :profile => "250x400",
                                          :thumb => "80x80",
                                          :small => "40x40"},
                            :url  => "/assets/avatars/:id/:style/:basename.:extension",
                            :path => ":rails_root/public/assets/avatars/:id/:style/:basename.:extension"
  
  has_many :pieces, :dependent => :destroy
  has_many :outfits, :dependent => :destroy
  
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nill if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user :nil
  end

  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
      
  private
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
  
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @title = "Users"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @pieces = @user.pieces
    @title = @user.name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @title = "Sign up"
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @title = "Edit User"
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        @title = "Sign up"
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    @title = @user.name
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
  
  def pieces
    @title = "Pieces"
    @user = User.find(params[:id])
    @users = @user.pieces
    render 'show_pieces'
  end
  
  def svpply
    @title = "svpply"
    @user = current_user
    render 'svpply'
  end  
  
  def multiple_create
    
    @user = current_user
    
    if params[:pieces].is_a?(Hash)
      @piece_hashes = params[:pieces].values
    else
      @piece_hashes = params[:pieces]
    end

    @piece_hashes.each do |piece_hash|
      @piece = @user.pieces.new(piece_hash)
      @piece.image_from_url
      @piece.save
    end
    
    redirect_to @user
    
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id), :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete }, :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_user.html.erb
<%= link_to(user) do %>
	<div id = "user-thumb">
		<span class = "image"><%= image_tag user.avatar.url(:thumb) %></span>
		<ul>
			<li class = "name"><%= user.name %></li>
			<li class = "location"><%= user.location %></li>
		</ul>
		</span>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for(@user, :html => { :multipart => true }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Change picture: "%>
    <%= f.file_field :avatar%>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirm %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Location</th>
    <th>About</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.location %></td>
    <td><%= user.about %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

  <%= form_for(@user, :html => { :multipart => true }) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class = "field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class = "field">
      <%= f.label "Choose a profile picture: " %>
      <%= f.file_field :avatar %>
	</div>
    <div class = "field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class = "field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class = "field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class "actions">
      <%= f.submit "Sign up "%>
    </div>
  <% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id = "user-info">

<span class = "avatar">
<%= image_tag @user.avatar.url(:profile) %>
</span>
<span class = "personal">
<h1>
  <%= @user.name %>
</h1>

<p>
<h2>
  <%= @user.location %>
</h2>
</p>

<p>
  <%= @user.about %>
</p>

</span>

<span class = "stats">

<%= render 'shared/stats' %>
<%= render 'follow_form' if signed_in? %>
<p>
<%= @user.pieces.count %> pieces
<%= link_to "View All", user_pieces_path(@user) %>	
<%= link_to "New", new_user_piece_path(current_user) %>
</p>
<p>
<%= @user.outfits.count %> outfits
<%= link_to "View All", user_outfits_path(@user) %>	
<%= link_to "New", new_user_outfit_path(current_user) %>	
</p>

<p>
<%= link_to "Import pieces from Svpply", svpply_user_path(current_user)%>
</p>


</span>
<%= link_to 'Edit', edit_user_path(current_user) %> |
<%= link_to 'Back', users_path %>

</div>

<div id = "feed">
	<ul>
	<%= @user.outfits.each do |outfit| %>
			<%= render outfit %>
	<% end %>
	</ui>
</div>

app/views/users/show_follow.html.erb
<h1><%= @title %></h1>

<% unless @users.empty? %>
<ul>
<% @users.each do |user| %>
	<li>
	<%= render user %>
	</li>
<% end %>
</ul>
<% end %>

app/views/users/svpply.html.erb
<h1><%= @title %></h1>

<button onclick="sync_svpply()">sync</button>