config/routes.rb
Outft::Application.routes.draw do
  
  get "sessions/new"
  
  resources :dashboard
  resources :outfits
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    resources :pieces
    resources :outfits
    member do
      get :following, :followers
      get :svpply
      post :multiple_create
    end
  end
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  get "home/index"

  root :to => 'home#index'

end

app/models/piece.rb
require 'open-uri'

class Piece < ActiveRecord::Base
  attr_accessible :name, :link, :image, :image_remote_url
  belongs_to :user
  has_and_belongs_to_many :outfits 
  default_scope :order => "created_at DESC"
  has_attached_file :image, 
:styles => { :big => ["300x300", :jpg], :thumb => ["80x80", :jpg]},
  :url  => "/assets/images/:id/:style/:basename.:extension",
  :path => ":rails_root/public/assets/images/:id/:style/:basename.:extension"
  
  def image_from_url
      self.image = open(self.image_remote_url)
  end

  
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  
  def index
    @user = User.find(params[:user_id])
    @pieces = @user.pieces
    @title = "Pieces"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pieces }
    end
  end
  
  def new
    @piece = Piece.new
    @user = current_user
    @title = "New Piece"
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @piece }
    end
  end
  
  def show
    @piece = Piece.find(params[:id])
    @title = @piece.name
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @piece }
    end
  end
    
  def create
    @user = User.find(params[:user_id])
    @piece = @user.pieces.create(params[:piece])
    redirect_to user_path(@user)
  end
    
  def destroy
    @user = User.find(params[:user_id])
    @piece = @user.pieces.find(params[:id])
    @piece.destroy
    redirect_to user_path(@user)
  end  
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/_form.html.erb
<%= form_for([@user, @user.pieces.build], :html => { :multipart => true }) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class = "field">
    <%= f.label "Choose an image: " %>
    <%= f.file_field :image %>
	</div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces/_piece.html.erb
<%= link_to(user_piece_path(piece.user, piece)) do %>

	<div id = "piece-thumb">
		<li>
		<p>
			<%= image_tag(piece.image.url(:thumb)) %> 
		<p>
  			<b>Name:</b>
  			<%= piece.name %>
		</p>

		<p>
  			<b>Link:</b>
  			<%= piece.link %>
		</p>

		<p>
  			<%= link_to 'Destroy Piece', [piece.user, piece], :confirm => 'Are you sure?', :method => :delete %>
		</p>
		</li>
	</div>

<% end %>

app/views/pieces/index.html.erb
<h1>Listing pieces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Link</th>
	<th>view</th>

  </tr>

<% @pieces.each do |piece| %>
  <tr>
    <td><%= piece.name %></td>
    <td><%= piece.link %></td>
	<td><%= link_to "view", user_piece_path(piece.user, piece) %></td>
	<td><%= link_to 'Destroy Piece', [piece.user, piece], :confirm => 'Are you sure?', :method => :delete %></td>

  </tr>
<% end %>
</table>

app/views/pieces/new.html.erb
<div id = "new-piece">
<%= render "form" %>
</div>

app/views/pieces/show.html.erb
<%= render @piece %>